services:
  - type: web
    name: wellness-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask run --host=0.0.0.0 --port=10000"
    envVars:
      - key: DATABASE_URL
        value: YOUR_POSTGRES_DB_URL
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
