"""Add score column to Mood table

Revision ID: f9891200315b
Revises: 41dd23afa466
Create Date: 2025-07-25 14:44:15.031665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9891200315b'
down_revision = '41dd23afa466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
